= CalConnect Standard: AsciiUnits syntax specification
:title: AsciiUnits syntax specification
:docnumber: 36810
:copyright-year: 2025
:doctype: standard
:edition: 1
:status: committee-draft
:revdate: 2025-03-14
:published-date: 2025-03-14
:technical-committee: UnitsML
:fullname: Ronald Tse
:surname: Tse
:givenname: Ronald
:affiliation: Ribose Inc.
:imagesdir: images
:mn-document-class: cc
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:

include::00-foreword.adoc[]

== Introduction

UnitsML is a suite of technologies that facilitate digital processing of units
of measurement and measurement quantities.

AsciiUnits is a text-based syntax for representing units of measurement in a
compact and human-readable format, designed to be fully compatible with and
interoperable with the UnitsML XML language.

== Scope

AsciiUnits syntax is designed to be simple and intuitive, allowing users to
express complex unit expressions using a straightforward notation.

[bibliography]
== Normative references

* [[[unitsml-xml,UnitsML XML schema]]], https://www.unitsml.org

== Terms and definitions

=== unit

standard quantity used to express a physical quantity

=== basic unit

unit not derived from other units

=== composite unit

unit derived from two or more basic units conjoined by multiplication or division

=== prefix

modifier to a unit with a fixed factor

=== quantity

type of measurement that is represented by a unit

[example]
distance, moment of force, temperature, energy.

=== dimension

basic physical quantity that can be expressed in terms of fundamental
quantities

[example]
length, mass, time, plane angle.


=== unit name

name of a unit

=== unit symbol

abbreviated representation of a unit

=== unit reference

reference identifier to a unit in a database

=== unit dimensions

fundamental quantities to which the unit applies


== Principles

AsciiUnits follows the following key principles to ensure clarity and usability
in representing units.

Typability:: Symbols are meant to be easily typed on standard keyboards,
avoiding complex characters or symbols.

Non-ambiguous:: Unit representation and composure syntax should lead to exactly
one interpretation, ensuring that each expression has an unambiguous meaning.

Extensible:: New units and new prefixes can be added to the system without
changing the syntax.



== Representable elements

=== General

AsciiUnits allows for the encoding of the following types of elements:

* Unit systems
* Units
* Dimensions
* Quantities
* Prefixes in conjunction with units

=== Unit systems

A unit system is a collection of units of measure that forms a coherent
framework for converting between different units of measurement.

UnitsML defines the following unit systems.

.UnitsML unit systems
|===
| ID | Name | Acceptable to be used in the SI system

| `SI_base` | SI | true
| `SI_derived_special` | SI-derived special | true
| `SI_derived_non-special` | SI-derived non-special | true
| `non-SI_acceptable` | non-SI but acceptable to be used together | true
| `non-SI_not_acceptable` | non-SI and unacceptable to be used together | false

|===

Each unit in UnitsML belongs to exactly one unit system.


=== Units

The AsciiUnits syntax is designed to represent a wide range of units of
measurement and their combinations.

It includes:

* Basic units: Simple units and prefixed units

* Composite units: Units formed by combining basic units through mathematical
  operations

Basic units available to AsciiUnits are sourced from UnitsDB.

UnitsDB is a comprehensive database of units of measurement and their relationships, which
is used to define the units and prefixes available in AsciiUnits for various applications.

NOTE: UnitsDB is a part of the UnitsML project and is maintained by CalConnect TC UNITS.

[[si-prefixes]]
=== Prefixes

A prefix is a modifier to a unit that indicates a fixed factor by which the unit
is multiplied.

Prefixes can be used in conjunction with units to create prefixed units.

The BIPM SI prefixes are used in AsciiUnits, which include the following:

.SI prefixes in base 10
|===
.2+| Prefix .2+| Symbol .2+| Factor 4+| Representations
| ASCII | HTML | LaTeX | Unicode

| quetta | Q      | 10^30 | `Q` | `Q` | `Q` | `Q`
| ronna  | R      | 10^27 | `R` | `R` | `R` | `R`
| yotta  | Y      | 10^24 | `Y` | `Y` | `Y` | `Y`
| zetta  | Z      | 10^21 | `Z` | `Z` | `Z` | `Z`
| exa    | E      | 10^18 | `E` | `E` | `E` | `E`
| peta   | P      | 10^15 | `P` | `P` | `P` | `P`
| tera   | T      | 10^12 | `T` | `T` | `T` | `T`
| giga   | G      | 10^9  | `G` | `G` | `G` | `G`
| mega   | M      | 10^6  | `M` | `M` | `M` | `M`
| kilo   | k      | 10^3  | `k` | `k` | `k` | `k`
| hecto  | h      | 10^2  | `h` | `h` | `h` | `h`
| deka   | da     | 10^1  | `da` | `da` | `da` | `da`
| deci   | d      | 10^-1 | `d` | `d` | `d` | `d`
| centi  | c      | 10^-2 | `c` | `c` | `c` | `c`
| milli  | m      | 10^-3 | `m` | `m` | `m` | `m`
| micro  | u      | 10^-6 | `u` | `&micro;` | `$mu$` | `μ`
| nano   | n      | 10^-9 | `n` | `n` | `n` | `n`
| pico   | p      | 10^-12 | `p` | `p` | `p` | `p`
| femto  | f      | 10^-15 | `f` | `f` | `f` | `f`
| atto   | a      | 10^-18 | `a` | `a` | `a` | `a`
| zepto  | z      | 10^-21 | `z` | `z` | `z` | `z`
| yocto  | y      | 10^-24 | `y` | `y` | `y` | `y`
| ronto  | r      | 10^-27 | `r` | `r` | `r` | `r`
| quecto | q      | 10^-30 | `q` | `q` | `q` | `q`
|===

.SI prefixes in binary
|===
.2+| Prefix .2+| Symbol .2+| Factor 4+| Representations
| ASCII | HTML | LaTeX | Unicode

| kibi  | Ki     | 2^10  | `Ki` | `Ki` | `Ki` | `Ki`
| mebi  | Mi     | 2^20  | `Mi` | `Mi` | `Mi` | `Mi`
| gibi  | Gi     | 2^30  | `Gi` | `Gi` | `Gi` | `Gi`
| tebi  | Ti     | 2^40  | `Ti` | `Ti` | `Ti` | `Ti`
| pebi  | Pi     | 2^50  | `Pi` | `Pi` | `Pi` | `Pi`
| exbi  | Ei     | 2^60  | `Ei` | `Ei` | `Ei` | `Ei`
| zebi  | Zi     | 2^70  | `Zi` | `Zi` | `Zi` | `Zi`
| yobi  | Yi     | 2^80  | `Yi` | `Yi` | `Yi` | `Yi`

|===


=== Dimensions

A dimension is a physical quantity that can be expressed in terms of
fundamental quantities.

Basic dimensions are described with only one quantity. More complex dimensions
require multiple quantities to be expressed.

Dimensions are represented in AsciiUnits using the `dim_` prefix followed by
the dimension name.

The collection of dimensions is defined in the UnitsDB database.
Each dimension is represented by a unique identifier in the database,
of the pattern `NISTd{n}`.


=== Quantities

A quantity is a type of measurement that is represented by a unit.

Each quantity is associated with one or more quantity names, exactly one
dimension, and one or more units of measurement.

The collection of quantities is defined in the UnitsDB database.
Each quantity is represented by a unique identifier in the database,
of the pattern `NISTq{n}`.


== Architecture

=== General

AsciiUnits is a text-based syntax for representing units of measurement.

There are two types of representable forms in AsciiUnits:

* Units
* Values of units

=== Statement

An AsciiUnits statement is a sequence of characters that represents a unit or
a value of a unit.

[example]
====
[source]
----
kg # kilogram
um # micrometer (meter + prefix of micro)
degK # degree kelvin
----
====

=== Units

A unit statement represented in the AsciiUnits language is composed of up to 3
types of elements in the UnitsML model structure.

* `Unit`, which represents the unit itself
* `Dimension`, which represents the dimension of the unit
* `Quantity`, which represents the quantity being described


=== Values of units

A value of a unit is a number that represents a measurement in that unit.

A value consists of a numerical component and a unit. For example, in "2.3 kg,"
"2.3" is the value representing the quantity and "kg" is the unit.

[example]
====
[source]
----
1.5 m # 1.5 meters
2.3 kg # 2.3 kilograms
3.0 m/s # 3.0 meters per second
----
====

AsciiUnits 1.0 does not support encoding of values of units.
This may be added in a future version.

== AsciiUnits prefixes

AsciiUnits statements support the use of prefixes as standalone
elements.

Prefixes elements are indicated with a prefix of `-` after the prefix code.

Syntax:

[source]
----
{prefix-code}-
----

Where,

`{prefix-code}`:: is the prefix code
`-`:: indicates that there is no unit associated with the prefix

[example]
====
AsciiUnits statement (for deci):

[source]
----
d-
----

XML:

[source,xml]
----
<Prefix xmlns="https://schema.unitsml.org/unitsml/1.0" prefixBase="10" prefixPower="-1" xml:id="NISTp10_-1">
  <PrefixName xml:lang="en">deci</PrefixName>
  <PrefixSymbol type="ASCII">d</PrefixSymbol>
  <PrefixSymbol type="unicode">d</PrefixSymbol>
  <PrefixSymbol type="LaTeX">d</PrefixSymbol>
  <PrefixSymbol type="HTML">d</PrefixSymbol>
</Prefix>
----
====

[example]
====
AsciiUnits statement (for deca):

[source]
----
da-
----

XML:

[source,xml]
----
<Prefix xmlns="https://schema.unitsml.org/unitsml/1.0" prefixBase="10" prefixPower="1" xml:id="NISTp10_1">
  <PrefixName xml:lang="en">deka</PrefixName>
  <PrefixSymbol type="ASCII">da</PrefixSymbol>
  <PrefixSymbol type="unicode">da</PrefixSymbol>
  <PrefixSymbol type="LaTeX">da</PrefixSymbol>
  <PrefixSymbol type="HTML">da</PrefixSymbol>
</Prefix>
----
====


== AsciiUnits dimensions

=== General

AsciiUnits statements support the use of dimensions as standalone
elements, that are not associated with any unit.

=== Basic dimensions

Dimensions elements are indicated with a prefix of `dim_`.

Syntax:

[source]
----
dim_{dimension-code}
----

Where,

`{dimension-code}`:: is the dimension code

[example]
====
[source]
----
dim_L       # length dimension
dim_Theta   # temperature dimension
dim_T       # time dimension
----
====

[example]
====
AsciiUnits statement (for length):

[source]
----
dim_L       # length dimension
----

XML:

[source,xml]
----
<Dimension xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="D_L">
  <Length symbol="L" powerNumerator="1"/>
</Dimension>
----
====


=== Dimensions with mathematical operations

Dimension elements can be expressed with mathematic operation adjustments.

The supported operations are:

* `*` for addition
* `/` for subtraction
* `^` for power
* `sqrt()` for square root

[example]
====
[source]
----
dim_L^2         # squared length dimension
dim_Theta^10    # temperature dimension to power 10
sqrt(dim_Theta) # square root of temperature dimension
----
====


[example]
====
AsciiUnits statement (for squared length):

[source]
----
dim_L^2
----

XML:

[source,xml]
----
<Dimension xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="D_L2">
  <Length symbol="L" powerNumerator="2"/>
</Dimension>
----
====

[example]
====
AsciiUnits statement (for square root of temperature):

[source]
----
sqrt(dim_Theta)
----

XML:

[source,xml]
----
<Dimension xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="D_Theta0.5">
  <ThermodynamicTemperature symbol="Theta" powerNumerator="0.5"/>
</Dimension>
----
====

=== Composed dimensions

Composed dimensions are formed by combining more than one basic dimensions
through mathematical operations.

[example]
====
[source]
----
dim_Theta*dim_L^2
----
====

[example]
====
AsciiUnits statement (for temperature times squared length):

[source]
----
dim_Theta*dim_L^2
----

XML:

[source,xml]
----
<Dimension xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="D_L2Theta">
  <Length symbol="L" powerNumerator="2"/>
  <ThermodynamicTemperature symbol="Theta" powerNumerator="1"/>
</Dimension>
----
====



== AsciiUnits units

=== General

* Prefixes are automatically parsed
* Dimensions are automatically calculated based on the prefixes and units represented

TODO: Elaborate this section!


=== Basic units

Basic units are the fundamental units of measurement that are not derived from
other units.

These units have the following characteristics:

* They are defined as individual entries in the UnitsDB database.

* Their `RootUnit` element contains a single `EnumeratedRootUnit` element, which
  represents the unit itself, with the `unit` attribute set to the unit name,
  with `powerNumerator` and `powerDenominator` set to 1.

Syntax:

[source]
----
{unit-code}
----

Where,

`{unit-code}`:: is the unit code


.Examples of basic units
[example]
====
[source]
----
m       # meter
s       # second
Hz      # hertz
K       # kelvin
rad     # radian
----
====

The XML representation of an AsciiUnits basic unit is demonstrated below.

* Basic units will not have a `<Prefix>` element since they are not prefixed
units.

* The `<Dimension>` element is automatically generated based on the unit code.


.AsciiUnits representation for `m`
[example]
====
AsciiUnits statement:

[source,ascii]
----
m
----

XML:

[source,xml]
----
<Unit xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="U_NISTu1" dimensionURL="#NISTd1">
  <UnitSystem name="SI" type="SI_derived" xml:lang="en-US"/>
  <UnitName xml:lang="en">meter</UnitName>
  <UnitSymbol type="HTML">m</UnitSymbol>
  <UnitSymbol type="MathMl">
    <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
      <mi mathvariant="normal">m</mi>
    </math>
  </UnitSymbol>
</Unit>

<Dimension xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="NISTd1">
  <Length symbol="L" powerNumerator="1"/>
</Dimension>
----
====

.AsciiUnits representation for `Hz`
[example]
====
AsciiUnits statement:

[source,ascii]
----
Hz
----

XML:

[source,xml]
----
<Unit xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="U_NISTu31" dimensionURL="#NISTd24">
  <UnitSystem name="SI" type="SI_derived" xml:lang="en-US"/>
  <UnitName xml:lang="en">hertz</UnitName>
  <UnitSymbol type="HTML">Hz</UnitSymbol>
  <UnitSymbol type="MathMl">
    <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
      <mi mathvariant="normal">Hz</mi>
    </math>
  </UnitSymbol>
</Unit>

<Dimension xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="NISTd24">
  <Time symbol="T" powerNumerator="-1"/>
</Dimension>

<Quantity xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="NISTq45" quantityType="base" dimensionURL="#NISTd24">
  <QuantityName xml:lang="en-US">frequency</QuantityName>
</Quantity>
----
====


=== Prefixed units

A prefixed unit is a unit that has a prefix attached to it, indicating a
fixed factor by which the unit is multiplied.

Prefixes are defined in the UnitsDB database and are represented in the XML
representation of the unit.

NOTE: AsciiUnits only support prefixes defined by the BIPM in the SI Brochure,
as described in <<si-prefixes>>.

Prefixes are automatically parsed in AsciiUnits.

Syntax:

[source]
----
{prefix-code}{unit-code}
----

Where,

`{prefix-code}`:: is the prefix code
`{unit-code}`:: is the unit code


[source]
----
kg      # kilogram
mm      # millimeter
mW      # milliwatt
----

The XML representation of an AsciiUnits prefixed unit is demonstrated below.

* Prefixed units will have a `<Prefix>` element since they are prefixed.

* The `<Dimension>` element is automatically generated based on the unit and the prefix.


.AsciiUnits representation for `kg`
[example]
====
AsciiUnits statement:

[source,ascii]
----
kg
----

XML:

[source,xml]
----
<Unit xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="U_NISTu2" dimensionURL="#NISTd2">
  <UnitSystem name="SI" type="SI_base" xml:lang="en-US"/>
  <UnitName xml:lang="en">kilogram</UnitName>
  <UnitSymbol type="HTML">kg</UnitSymbol>
  <UnitSymbol type="MathMl">
    <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
      <mi mathvariant="normal">kg</mi>
    </math>
  </UnitSymbol>
  <RootUnits>
    <EnumeratedRootUnit unit="gram" prefix="k"/>
  </RootUnits>
</Unit>

<Prefix xmlns="https://schema.unitsml.org/unitsml/1.0" prefixBase="10" prefixPower="3" xml:id="NISTp10_3">
  <PrefixName xml:lang="en">kilo</PrefixName>
  <PrefixSymbol type="ASCII">k</PrefixSymbol>
  <PrefixSymbol type="unicode">k</PrefixSymbol>
  <PrefixSymbol type="LaTeX">k</PrefixSymbol>
  <PrefixSymbol type="HTML">k</PrefixSymbol>
</Prefix>

<Dimension xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="NISTd2">
  <Mass symbol="M" powerNumerator="1"/>
</Dimension>

<Quantity xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="NISTq2" quantityType="base" dimensionURL="#NISTd2">
  <QuantityName xml:lang="en-US">mass</QuantityName>
</Quantity>
----
====


=== Composite units

==== General

Composite units are units that are derived from two or more basic units
conjoined by a mathematical operation.

Mathematical operations are represented in AsciiUnits using the following
symbols:

* `*` for multiplication
* `/` for division
* `^` for exponentiation
* `sqrt()` for square root
* `()` for grouping

The XML representation of an AsciiUnits composite unit:

* Prefixed units inside the composite will have a `<Prefix>` element.

* The `<Dimension>` element is automatically generated based on the final
mathematical evaluation of the involved units and prefixes.


==== Multiplication

Units are multiplied using `*`

[example]
====
[source]
----
kg*m    # kilogram times meter
----
====

[example]
====
AsciiUnits statement (for ampere times coulomb):

----
A*C
----

XML:

[source,xml]
----
<Unit xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="U_A.C" dimensionURL="#D_M3I4">
  <UnitSystem name="SI" type="SI_derived" xml:lang="en-US"/>
  <UnitName xml:lang="en">A*C</UnitName>
  <UnitSymbol type="HTML">A&#x22c5;C</UnitSymbol>
  <UnitSymbol type="MathMl">
    <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
      <mi mathvariant="normal">A</mi>
      <mo>&#x22c5;</mo>
      <mi mathvariant="normal">C</mi>
    </math>
  </UnitSymbol>
  <RootUnits>
    <EnumeratedRootUnit unit="ampere"/>
    <EnumeratedRootUnit unit="coulomb" powerNumerator="1"/>
  </RootUnits>
</Unit>

<Dimension xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="D_M3I4">
  <Mass symbol="M" powerNumerator="1"/>
  <ElectricCurrent symbol="I" powerNumerator="4"/>
</Dimension>
----
====


==== Division

Units are divided using `/`

[example]
====
AsciiUnits statement (for GHz per volt):

[source]
----
GHz//V
----

XML:

[source,xml]
----
<Unit xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="U_GHz.V-1" dimensionURL="#D_L-2M-1T2I">
  <UnitSystem name="SI" type="SI_derived" xml:lang="en-US"/>
  <UnitName xml:lang="en">GHz*V^-1</UnitName>
  <UnitSymbol type="HTML">GHz&#x22c5;V<sup>&#x2212;1</sup></UnitSymbol>
  <UnitSymbol type="MathMl">
    <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
      <mi mathvariant="normal">GHz</mi>
      <mo>&#x22c5;</mo>
      <msup>
        <mrow>
          <mi mathvariant="normal">V</mi>
        </mrow>
        <mrow>
          <mo>&#x2212;</mo>
          <mn>1</mn>
        </mrow>
      </msup>
    </math>
  </UnitSymbol>
  <RootUnits>
    <EnumeratedRootUnit unit="hertz" prefix="G"/>
    <EnumeratedRootUnit unit="volt" powerNumerator="-1"/>
  </RootUnits>
</Unit>

<Prefix xmlns="https://schema.unitsml.org/unitsml/1.0" prefixBase="10" prefixPower="9" xml:id="NISTp10_9">
  <PrefixName xml:lang="en">giga</PrefixName>
  <PrefixSymbol type="ASCII">G</PrefixSymbol>
  <PrefixSymbol type="unicode">G</PrefixSymbol>
  <PrefixSymbol type="LaTeX">G</PrefixSymbol>
  <PrefixSymbol type="HTML">G</PrefixSymbol>
</Prefix>

<Dimension xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="D_L-2M-1T2I">
  <Length symbol="L" powerNumerator="-2"/>
  <Mass symbol="M" powerNumerator="-1"/>
  <Time symbol="T" powerNumerator="2"/>
  <ElectricCurrent symbol="I" powerNumerator="1"/>
</Dimension>
----
====

==== Grouping

Parentheses define order of operations

[source]
----
K/(kg*m)    # kelvin divided by (kilogram times meter)
J/(kg*K)    # joule per (kilogram kelvin)
----

[example]
====
AsciiUnits statement (for joule per kilogram kelvin):

[source]
----
unitsml(m^(-2))
----

XML:

[source,xml]
----
<Unit xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="U_m-2" dimensionURL="#D_L-2">
  <UnitSystem name="SI" type="SI_derived" xml:lang="en-US"/>
  <UnitName xml:lang="en">m^-2</UnitName>
  <UnitSymbol type="HTML">m<sup>&#x2212;2</sup></UnitSymbol>
  <UnitSymbol type="MathMl">
    <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
      <msup>
        <mrow>
          <mi mathvariant="normal">m</mi>
        </mrow>
        <mrow>
          <mo>&#x2212;</mo>
          <mn>2</mn>
        </mrow>
      </msup>
    </math>
  </UnitSymbol>
</Unit>

<Dimension xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="D_L-2">
  <Length symbol="L" powerNumerator="-2"/>
</Dimension>
----
====


=== Exponents

Syntax:

[source]
----
{unit-code}^{exponent}
----

Where,

`{unit-code}`:: is the unit code
`{exponent}`:: is the exponent

[example]
====
[source]
----
m^2     # square meter
----

XML:

[source,xml]
----
<Unit xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="U_m2" dimensionURL="#D_L2">
  <UnitSystem name="SI" type="SI_derived" xml:lang="en-US"/>
  <UnitName xml:lang="en">m^2</UnitName>
  <UnitSymbol type="HTML">m<sup>&#x2212;2</sup></UnitSymbol>
  <UnitSymbol type="MathMl">
    <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
      <msup>
        <mrow>
          <mi mathvariant="normal">m</mi>
        </mrow>
        <mrow>
          <mo>&#x2212;</mo>
          <mn>2</mn>
        </mrow>
      </msup>
    </math>
  </UnitSymbol>
</Unit>

<Dimension xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="D_L2">
  <Length symbol="L" powerNumerator="2"/>
</Dimension>
----
====

Negative exponents are allowed.

[example]
====
[source]
----
kg^-2     # per kilogram
kg^(-2)   # per kilogram with group
----

XML:

[source,xml]
----
<Unit xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="U_kg-2" dimensionURL="#D_M-2">
  <UnitSystem name="SI" type="SI_base" xml:lang="en-US"/>
  <UnitName xml:lang="en">kg^-2</UnitName>
  <UnitSymbol type="HTML">kg<sup>&#x2212;2</sup></UnitSymbol>
  <UnitSymbol type="MathMl">
    <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
      <msup>
        <mrow>
          <mi mathvariant="normal">kg</mi>
        </mrow>
        <mrow>
          <mo>&#x2212;</mo>
          <mn>2</mn>
        </mrow>
      </msup>
    </math>
  </UnitSymbol>
  <RootUnits>
    <EnumeratedRootUnit unit="gram" prefix="k" powerNumerator="-2"/>
  </RootUnits>
</Unit>

<Prefix xmlns="https://schema.unitsml.org/unitsml/1.0" prefixBase="10" prefixPower="3" xml:id="NISTp10_3">
  <PrefixName xml:lang="en">kilo</PrefixName>
  <PrefixSymbol type="ASCII">k</PrefixSymbol>
  <PrefixSymbol type="unicode">k</PrefixSymbol>
  <PrefixSymbol type="LaTeX">k</PrefixSymbol>
  <PrefixSymbol type="HTML">k</PrefixSymbol>
</Prefix>

<Dimension xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="D_M-2">
  <Mass symbol="M" powerNumerator="-2"/>
</Dimension>
----
====


=== Square root

Using `sqrt()` function.

.Statement with square root on a basic unit
[example]
====
AsciiUnits statement (for square root of hertz):

[source]
----
sqrt(Hz)
----

XML:

[source,xml]
----
<Unit xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="U_Hz0.5" dimensionURL="#D_T-0.5">
  <UnitSystem name="SI" type="SI_derived" xml:lang="en-US"/>
  <UnitName xml:lang="en">Hz^0.5</UnitName>
  <UnitSymbol type="HTML">Hz<sup>0.5</sup></UnitSymbol>
  <UnitSymbol type="MathMl">
    <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
      <msup>
        <mrow>
          <mi mathvariant="normal">Hz</mi>
        </mrow>
        <mrow>
          <mn>0.5</mn>
        </mrow>
      </msup>
    </math>
  </UnitSymbol>
</Unit>

<Dimension xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="D_T-0.5">
  <Time symbol="T" powerNumerator="-0.5"/>
</Dimension>
----
====

.Statement with square root on a prefixed unit
[example]
====
AsciiUnits statement (for square root of millimeter):

[source]
----
sqrt(mm)
----

XML:

[source,xml]
----
<Unit xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="U_mm0.5" dimensionURL="#D_L0.5">
  <UnitSystem name="SI" type="SI_derived" xml:lang="en-US"/>
  <UnitName xml:lang="en">mm^0.5</UnitName>
  <UnitSymbol type="HTML">mm<sup>0.5</sup></UnitSymbol>
  <UnitSymbol type="MathMl">
    <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
      <msup>
        <mrow>
          <mi mathvariant="normal">mm</mi>
        </mrow>
        <mrow>
          <mn>0.5</mn>
        </mrow>
      </msup>
    </math>
  </UnitSymbol>
  <RootUnits>
    <EnumeratedRootUnit unit="meter" prefix="m" powerNumerator="0.5"/>
  </RootUnits>
</Unit>

<Prefix xmlns="https://schema.unitsml.org/unitsml/1.0" prefixBase="10" prefixPower="-3" xml:id="NISTp10_-3">
  <PrefixName xml:lang="en">milli</PrefixName>
  <PrefixSymbol type="ASCII">m</PrefixSymbol>
  <PrefixSymbol type="unicode">m</PrefixSymbol>
  <PrefixSymbol type="LaTeX">m</PrefixSymbol>
  <PrefixSymbol type="HTML">m</PrefixSymbol>
</Prefix>

<Dimension xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="D_L0.5">
  <Length symbol="L" powerNumerator="0.5"/>
</Dimension>
----
====



=== Composed units

Composed units are formed by combining more than one basic unit through
mathematical operations.

[example]
====
AsciiUnits statement (for joule per kilogram kelvin):

[source]
----
J/kg*K
----

XML:

[source,xml]
----
<Unit xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="U_NISTu13.u27p10_3e-1/1.u5e-1/1" dimensionURL="#D_L2M0T-2Theta-1">
  <UnitSystem name="SI" type="SI_derived" xml:lang="en-US"/>
  <UnitName xml:lang="en">joule per kilogram kelvin</UnitName>
  <UnitSymbol type="HTML">J&#x22c5;kg<sup>&#x2212;1</sup>&#x22c5;K<sup>&#x2212;1</sup></UnitSymbol>
  <UnitSymbol type="MathMl">
    <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
      <mi mathvariant="normal">J</mi>
      <mo>&#x22c5;</mo>
      <msup>
        <mrow>
          <mi mathvariant="normal">kg</mi>
        </mrow>
        <mrow>
          <mo>&#x2212;</mo>
          <mn>1</mn>
        </mrow>
      </msup>
      <mo>&#x22c5;</mo>
      <msup>
        <mrow>
          <mi mathvariant="normal">K</mi>
        </mrow>
        <mrow>
          <mo>&#x2212;</mo>
          <mn>1</mn>
        </mrow>
      </msup>
    </math>
  </UnitSymbol>
  <RootUnits>
    <EnumeratedRootUnit unit="joule"/>
    <EnumeratedRootUnit unit="gram" prefix="k" powerNumerator="-1"/>
    <EnumeratedRootUnit unit="kelvin" powerNumerator="-1"/>
  </RootUnits>
</Unit>

<Prefix xmlns="https://schema.unitsml.org/unitsml/1.0" prefixBase="10" prefixPower="3" xml:id="NISTp10_3">
  <PrefixName xml:lang="en">kilo</PrefixName>
  <PrefixSymbol type="ASCII">k</PrefixSymbol>
  <PrefixSymbol type="unicode">k</PrefixSymbol>
  <PrefixSymbol type="LaTeX">k</PrefixSymbol>
  <PrefixSymbol type="HTML">k</PrefixSymbol>
</Prefix>

<Dimension xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="NISTd40">
  <Length symbol="L" powerNumerator="2"/>
  <Time symbol="T" powerNumerator="-2"/>
  <ThermodynamicTemperature symbol="Theta" powerNumerator="-1"/>
</Dimension>

<Dimension xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="D_L2M0T-2Theta-1">
  <Length symbol="L" powerNumerator="2"/>
  <Mass symbol="M" powerNumerator="0"/>
  <Time symbol="T" powerNumerator="-2"/>
  <ThermodynamicTemperature symbol="Theta" powerNumerator="-1"/>
</Dimension>
----
====


=== Metadata in units

Metadata can be added after a comma after an AsciiUnits statement.

[example]
====
[source]
----
m, quantity: NISTq103               # meter with quantity reference
cal_th/cm^2, name: langley          # calorie thermal per square centimeter with name
cm*s^-2, symbol: cm cdot s^-2       # custom symbol representation
cm*s^-2, multiplier: xx             # custom multiplier
----
====

[example]
====
AsciiUnits statement (for candela steradian per square meter),
with a custom symbol representation:

[source]
----
unitsml(cd*sr*m^(-2),symbol:cd cdot sr cdot m^(-2))
----

XML:

[source,xml]
----
<Unit xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="U_cd.sr.m-2" dimensionURL="#D_L-2J">
  <UnitSystem name="SI" type="SI_derived" xml:lang="en-US"/>
  <UnitName xml:lang="en">cd*sr*m^-2</UnitName>
  <UnitSymbol type="HTML">cd&#x22c5;sr&#x22c5;m<sup>&#x2212;2</sup></UnitSymbol>
  <UnitSymbol type="MathMl">
    <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
      <mi mathvariant="normal">cd</mi>
      <mo>&#x22c5;</mo>
      <mi mathvariant="normal">sr</mi>
      <mo>&#x22c5;</mo>
      <msup>
        <mrow>
          <mi mathvariant="normal">m</mi>
        </mrow>
        <mrow>
          <mo>&#x2212;</mo>
          <mn>2</mn>
        </mrow>
      </msup>
    </math>
  </UnitSymbol>
  <RootUnits>
    <EnumeratedRootUnit unit="candela"/>
    <EnumeratedRootUnit unit="steradian"/>
    <EnumeratedRootUnit unit="meter" powerNumerator="-2"/>
  </RootUnits>
</Unit>

<Dimension xmlns="https://schema.unitsml.org/unitsml/1.0" xml:id="D_L-2J">
  <Length symbol="L" powerNumerator="-2"/>
  <LuminousIntensity symbol="J" powerNumerator="1"/>
</Dimension>
----
====


== Bibliography

