source "https://rubygems.org"

gem "lutaml",
    github: "lutaml/lutaml",
    branch: "update/xsd_support_metanorma_plugin"
gem "lutaml-model",
    github: "lutaml/lutaml-model",
    branch: "main"
gem "lutaml-xsd",
    github: "lutaml/lutaml-xsd",
    branch: "update/liquid_drop_methods"
gem "metanorma"
gem "metanorma-cli"
gem "metanorma-plugin-lutaml",
    github: "metanorma/metanorma-plugin-lutaml",
    branch: "feature/unitsml_liquid_filters"
gem "metanorma-standoc",
    github: "metanorma/metanorma-standoc",
    branch: "update/lutaml_xsd_preprocessor_support"
gem "metanorma-utils",
    github: "metanorma/metanorma-utils",
    branch: "main"
