{%# Documentation #%}

{%liquid
  assign item_attributes = item.attribute_elements
  assign used_by_items = item.used_by
%}
{% capture docs %}
{% for paragraph in item.annotation.documentation %}
{{ paragraph.content }}

{% endfor %}
{% endcapture %}

[[xsd_{{item.name}}]]
=== `{{ item.name }}`

==== Group

{{ docs }}

{% if used_by_items.size > 0 %}
This attribute group is used by:

{% for used_by in used_by_items %}
{% capture description %}
{% for paragraph in used_by.annotation.documentation %}
{{ paragraph.content }}

{% endfor %}
{% endcapture %}
@{{ used_by.name }}::
{% if description %}
+
--
{{ description }}
--
{% endif %}

{% endfor %}
{% endif %}

==== Attributes

{% if item_attributes.size > 0 %}
{% for attribute in item_attributes %}
{% capture attribute_docs %}
{% for paragraph in attribute.annotation.documentation %}
{{ paragraph.content }}

{% endfor %}
{% endcapture %}
`@{{ attribute.name | default: attribute.ref }}`:: {% if attribute.referenced_type %}`{{ attribute.referenced_type }}`{% endif %} `[{{ attribute.cardinality }}]`
{% if attribute_docs %}
+
--
{{ attribute_docs }}
--
{% endif %}

{% endfor %}
{% else %}
No attributes defined.
{% endif %}

.XSD source of `<{{ item.name }}>`

[source,xml]
-----
{{ item | to_xml_representation: skip_rendering_of }}
-----
