{%# Documentation #%}
{%liquid
  assign item_complex_type = item.referenced_complex_type
  assign item_attributes = item.attributes
  assign item_children = item.child_elements
  assign used_by_items = item.used_by
  assign elements = item_complex_type.direct_child_elements
%}
{% capture docs %}
{% for paragraph in item.annotation.documentation %}
{{ paragraph.content }}

{% endfor %}
{% endcapture %}

[[xsd_{{item.name}}]]
=== `<{{ item.name }}>`

==== General

{{ docs }}

{% if used_by_items.size > 0 %}
This element is used by:

{% for used_by in used_by_items %}
* {{ used_by.name }} (<<xsd_{{used_by.name}}>>)

{% endfor %}
{% endif %}

==== Attributes

{% if item_attributes.size > 0 %}
{% for attribute in item_attributes %}
{% capture attribute_docs %}
{% for paragraph in attribute.annotation.documentation %}
{{ paragraph.content }}

{% endfor %}
{% endcapture %}
`@{{ attribute.name | default: attribute.ref }}`:: {% if attribute.referenced_type %}`{{ attribute.referenced_type }}`{% endif %} `[{{ attribute.cardinality }}]`
{% if attribute_docs %}
+
--
{{ attribute_docs }}
--
{% endif %}

{% endfor %}
{% else %}
No attributes defined.
{% endif %}

==== Content model

This element is specified the type {{ item.type }} (<<xsd_{{item.type}}>>).

{% if item_children.size > 0 %}

{% for child in item_children %}
{% assign item_name = child.ref | default: child.name %}
{% if item_name %}
{% capture child_docs %}
{% for paragraph in child.annotation.documentation %}
{{ paragraph.content }}

{% endfor %}
{% endcapture %}

{{ item_name }}:: {% if child.referenced_type %}`{{ child.referenced_type }}`{% endif %} [{{ child.min_occurrences }}..{{ child.max_occurrences }}]
{% if child_docs %}
+
--
{{ child_docs }}
--
{% endif %}

{% else %}
{{ child }}

{% endif %}
{% endfor %}

{% else %}
No child elements defined.
{% endif %}


[example]
.Illustrative usage of `<{{ item.name }}>`
====
[source,xml]
-----
<{{item.name}}{% for attr in item_attributes %}
{%- capture type %}
{%- if attr.referenced_type %}
{{-  attr.referenced_type }}
{%- elsif attr.simple_type.restriction -%}
{{- attr.simple_type.restriction.base -}} (value comes from list: '{{ attr.simple_type.restriction.enumeration | map: "value" | join: "'|'" }}')
{%- elsif attr.simple_type.union -%}
{%- assign union = attr.simple_type.union -%}
{% capture enums %}
{%- for u_s_type in union.simple_type -%}
{% assign something = u_s_type.restriction %}
{{- u_s_type.restriction.enumeration | map: "value" | join: "'|'" -}}
{%- endfor -%}
{% endcapture %}
{{- union.member_types }} (value comes from list: {{ enums }})
{%- endif %}
{%- endcapture %}
  {{ attr.referenced_name }}="{{ type }}" [{{ attr.cardinality }}]
{%- endfor -%}
{%- if elements.size > 0 -%}
{% if item_attributes.size > 1 %}
>
{%- else -%}>{% endif %}
  {% if item_complex_type.mixed %}<!-- Mixed content -->{%- endif %}
{%- for child in elements -%}
  {%- if child.is_annotation? or child.is_attribute? or child.is_attribute_group? -%}
  {%- continue -%}
  {%- else %}
  {% render "child_elements", child: child -%}
  {% endif -%}
{%- endfor %}
</{{item.name}}>
{%- else %}
/>
{% endif %}
-----
====

.XSD source of `<{{ item.name }}>`
[source,xml]
-----
{{ item | to_xml_representation: skip_rendering_of }}
-----
