== Terms and definitions

=== basic element

fundamental component in the UnitsML framework, including unit, dimension, prefix, quantity, unit system, quantity kind, and type of interval/unit scale

=== composite expression

combination of multiple basic elements using mathematical operations such as multiplication, division, and exponentiation

=== NID

namespace identifier, registered with IANA for use with URNs

=== NSS

namespace specific string, the portion of a URN that follows the "urn:" <NID> ":" and conforms to the specification of the NID

=== unit

reference quantity with which other quantities of the same kind are compared to express their value

=== dimension

expression of the dependence of a physical quantity on the base quantities of a system of quantities, in the form of a product of powers of factors corresponding to the base quantities, omitting any numerical factors

=== prefix

named multiple or submultiple of a unit, used to form decimal multiples or submultiples of units

=== quantity

property of a phenomenon, body, or substance, where the property has a magnitude that can be expressed as a number and a reference

=== unit system

set of units, together with a set of equations relating them

=== quantity kind

aspect common to mutually comparable quantities

=== type of interval

specification of how values in a scale or interval are related to each other, such as logarithmic, linear, or discrete